import { useState } from "react"
import type { Screen } from "../../../types/navigation"
import { Button, Icon, Logo, PasswordField, Strength } from "../../../components/ui/primitives"
import { useVault } from "../../vault/VaultContext"
import { api } from "../../../lib/api"
import { getAccessToken, setVaultKey } from "../../../lib/auth"
import { reencryptVault } from "../../../lib/crypto"
export function Reset({ navigate, toast }: { navigate: (s: Screen) => void; toast: (s: string) => void }) {
  const { vault } = useVault(); const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false)
  async function submit() { if (next.length < 8) { setError("New Master Password must be at least 8 characters"); return }; if (next !== confirm) { setError("New Master Passwords do not match"); return }; setLoading(true); setError(""); try { const token = getAccessToken(); if (!token) throw new Error("Session expired"); const remote = await api.getVault(token); const salt = Uint8Array.from(atob(remote.kdf_salt), c => c.charCodeAt(0)); const { deriveVaultKey, decryptVault } = await import("../../../lib/crypto"); const oldKey = await deriveVaultKey(current, salt, remote.kdf_params); const decrypted = await decryptVault(remote.encrypted_data, oldKey); const result = await reencryptVault(decrypted, next); await api.updateVault({ encrypted_data: result.encryptedData, kdf_salt: result.kdf_salt, kdf_algorithm: result.kdf_algorithm, kdf_params: result.kdf_params }, token); setVaultKey(result.key); toast("Master Password updated"); navigate("vault") } catch { setError("Current Master Password is incorrect or the vault could not be updated") } finally { setLoading(false) } }
  return <div><button className="back-link in-app" onClick={() => navigate("vault")}>← Back to vault</button><div className="page-heading compact"><div><h1>Reset Master Password</h1><p>Choose a new password to protect your encrypted vault.</p></div></div><div className="form-card reset-form"><div className="form-grid single"><PasswordField label="Current Master Password" value={current} onChange={setCurrent} /><PasswordField label="New Master Password" value={next} onChange={setNext} /><Strength /><PasswordField label="Confirm New Master Password" value={confirm} onChange={setConfirm} /></div>{error && <div className="inline-error"><Icon name="alert" />{error}</div>}<div className="reset-actions"><Button variant="secondary" full onClick={() => navigate("vault")}>Cancel</Button><Button full onClick={() => void submit()} disabled={loading}>{loading ? "Updating..." : "Update Password"}</Button></div></div></div>
}
export function About({ navigate }: { navigate: (s: Screen) => void }) { return <div><button className="back-link in-app" onClick={() => navigate("vault")}>← Back to vault</button><div className="about-page"><div className="about-hero"><Logo large /><span className="version">Version 1.0.0</span><h1>About VaultX</h1><p>A privacy-focused password manager for generating, storing, and managing strong credentials through an encrypted vault.</p></div><div className="about-detail"><span className="detail-icon"><Icon name="shield" /></span><div><strong>Private by design</strong><p>Your vault is encrypted locally before synchronization. Only you can unlock it.</p></div></div><div className="about-detail"><span className="detail-icon"><Icon name="key" /></span><div><strong>Built for simplicity</strong><p>Essential password tools without unnecessary access to your data.</p></div></div><p className="about-team">Built by <strong>The Unlockers</strong></p></div></div> }
