import { useRef, useState, type FormEvent, type KeyboardEvent } from "react"
import type { Screen } from "../../../types/navigation"
import { api, ApiRequestError } from "../../../lib/api"
import { clearAuth, getAccessToken, getPendingEmail, setAccessToken, setPendingEmail, setVaultKey } from "../../../lib/auth"
import { createEmptyVault, deriveVaultKey, encryptVault, generateVaultSalt, metadataForSalt } from "../../../lib/crypto"
import { useVault } from "../../vault/VaultContext"
import { AuthShell, Button, Field, Icon, IconButton, Logo, PasswordField, Strength } from "../../../components/ui/primitives"

type Navigate = (screen: Screen) => void

export function Welcome({ next, login }: { next: () => void; login: () => void }) {
  return <div className="welcome"><div className="welcome-top"><span className="eyebrow">THE UNLOCKERS</span><button className="welcome-signin" onClick={login}>Sign in <Icon name="arrow" size={15} /></button></div><div className="welcome-visual"><div className="vault-rings"><div className="vault-core"><Logo large /></div><span className="orbit orbit-one" /><span className="orbit orbit-two" /></div><span className="privacy-chip"><Icon name="lock" size={15} />End-to-end encrypted</span></div><div className="welcome-copy"><span className="eyebrow">PRIVATE BY DESIGN</span><h1>Your passwords.<br />Securely yours.</h1><p>Generate, store, and manage strong passwords with a privacy-first encrypted vault.</p></div><div className="welcome-actions"><Button full onClick={next}>Get Started <Icon name="arrow" /></Button><div className="social-links"><button aria-label="GitHub"><Icon name="github" /></button><button aria-label="LinkedIn"><Icon name="linkedin" /></button><button aria-label="Twitter"><Icon name="twitter" /></button></div></div><p className="team-line">Built with care by <strong>The Unlockers</strong></p></div>
}

export function Signup({ navigate }: { navigate: Navigate }) {
  const [email, setEmail] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false)
  async function submit(e: FormEvent) { e.preventDefault(); const value = email.trim().toLowerCase(); if (!value.includes("@")) { setError("Enter a valid email address"); return }; setLoading(true); setError(""); try { await api.signup(value); setPendingEmail(value); navigate("verify") } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Unable to create account") } finally { setLoading(false) } }
  return <AuthShell title="Create your VaultX account" text="Start securing your online accounts with a private password vault." back={() => navigate("welcome")}><form className="form-stack" onSubmit={submit}><Field label="Email address" placeholder="you@example.com" value={email} onChange={v => { setEmail(v); setError("") }} icon="mail" error={error} /><Button full type="submit" disabled={loading}>{loading ? "Sending..." : "Send Verification Code"} {!loading && <Icon name="arrow" />}</Button></form><p className="auth-footer">Already have an account? <button onClick={() => navigate("login")}>Sign in</button></p><SecurityNote /></AuthShell>
}

export function Verify({ navigate, purpose = "signup" }: { navigate: Navigate; purpose?: "signup" | "login" }) {
  const [code, setCode] = useState(["", "", "", "", "", ""]); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const inputs = useRef<Array<HTMLInputElement | null>>([]); const email = getPendingEmail()
  function updateDigit(index: number, raw: string) { const digits = raw.replace(/\D/g, ""); if (!digits) { const next = [...code]; next[index] = ""; setCode(next); return }; const next = [...code]; digits.slice(0, 6 - index).split("").forEach((d, offset) => { next[index + offset] = d }); setCode(next); inputs.current[Math.min(index + digits.length, 5)]?.focus() }
  function keyDown(index: number, e: KeyboardEvent<HTMLInputElement>) { if (e.key === "Backspace" && !code[index] && index > 0) inputs.current[index - 1]?.focus(); if (e.key === "ArrowLeft" && index > 0) inputs.current[index - 1]?.focus(); if (e.key === "ArrowRight" && index < 5) inputs.current[index + 1]?.focus() }
  async function verify() { const otp = code.join(""); if (otp.length !== 6) { setError("Enter the 6-digit verification code"); return }; if (!email) { setError("Your verification session has expired"); return }; setLoading(true); setError(""); try { const response = purpose === "signup" ? await api.verifySignup(email, otp) : await api.verifyLogin(email, otp); setAccessToken(response.access_token); navigate(purpose === "signup" ? "master" : "unlock") } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Invalid verification code") } finally { setLoading(false) } }
  return <AuthShell eyebrow="STEP 1 OF 2" title="Verify your email" text={`We've sent a 6-digit verification code to ${maskEmail(email)}.`} back={() => navigate(purpose === "signup" ? "signup" : "login")}><div className="form-stack"><label className="field"><span className="field-label">Verification code</span><span className="otp-row">{code.map((digit, i) => <input key={i} ref={el => { inputs.current[i] = el }} aria-label={`Digit ${i + 1}`} inputMode="numeric" autoComplete={i === 0 ? "one-time-code" : "off"} maxLength={1} value={digit} onChange={e => updateDigit(i, e.target.value)} onKeyDown={e => keyDown(i, e)} onPaste={e => { e.preventDefault(); updateDigit(i, e.clipboardData.getData("text")) }} />)}</span></label>{error && <div className="inline-error"><Icon name="alert" />{error}</div>}<Button full onClick={verify} disabled={loading}>{loading ? "Verifying..." : "Verify & Continue"} {!loading && <Icon name="arrow" />}</Button></div><div className="resend"><button disabled={loading}>Resend Code</button><span>Request another code after cooldown</span></div><button className="subtle-link" onClick={() => navigate(purpose === "signup" ? "signup" : "login")}>Change email address</button></AuthShell>
}

export function Master({ navigate }: { navigate: Navigate }) {
  const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false)
  async function createVault() { if (password.length < 8) { setError("Master Password must be at least 8 characters"); return }; if (password !== confirm) { setError("Master Passwords do not match"); return }; const token = getAccessToken(); if (!token) { setError("Your session has expired. Please sign in again."); return }; setLoading(true); setError(""); try { const salt = generateVaultSalt(); const key = await deriveVaultKey(password, salt); const encrypted = await encryptVault(createEmptyVault(), key); await api.createVault({ encrypted_data: encrypted, ...metadataForSalt(salt) }, token); setVaultKey(key); navigate("vault") } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Unable to create your encrypted vault") } finally { setLoading(false) } }
  return <AuthShell eyebrow="STEP 2 OF 2" title="Create your Master Password" text="Your Master Password protects your encrypted vault. Make it strong and memorable." back={() => navigate("verify")}><div className="form-stack"><PasswordField label="Master Password" value={password} onChange={v => { setPassword(v); setError("") }} /><Strength /><PasswordField label="Confirm Master Password" value={confirm} onChange={v => { setConfirm(v); setError("") }} /><div className="notice"><Icon name="key" /><p><strong>Only you know this password</strong><span>VaultX cannot recover your Master Password. Keep it somewhere safe.</span></p></div>{error && <div className="inline-error"><Icon name="alert" />{error}</div>}<Button full onClick={createVault} disabled={loading}>{loading ? "Creating Vault..." : "Create Vault"} {!loading && <Icon name="arrow" />}</Button></div></AuthShell>
}

export function Login({ navigate }: { navigate: Navigate }) {
  const [email, setEmail] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false)
  async function submit() { const value = email.trim().toLowerCase(); if (!value.includes("@")) { setError("Enter a valid email address"); return }; setLoading(true); setError(""); try { await api.login(value); setPendingEmail(value); navigate("login-verify") } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Unable to start sign in") } finally { setLoading(false) } }
  return <AuthShell title="Welcome back" text="Sign in to your VaultX account to continue." back={() => navigate("welcome")}><div className="form-stack"><Field label="Email address" placeholder="you@example.com" value={email} onChange={v => { setEmail(v); setError("") }} icon="mail" error={error} /><Button full onClick={submit} disabled={loading}>{loading ? "Sending Code..." : "Continue"} {!loading && <Icon name="arrow" />}</Button></div><p className="auth-footer">New to VaultX? <button onClick={() => navigate("signup")}>Create an account</button></p></AuthShell>
}

export function LoginVerify({ navigate }: { navigate: Navigate }) { return <Verify navigate={navigate} purpose="login" /> }

export function Unlock({ navigate, onUnlocked }: { navigate: Navigate; onUnlocked: (key: CryptoKey) => void }) {
  const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const { unlock } = useVault()
  async function submit() { if (!password) { setError("Enter your Master Password"); return }; setLoading(true); setError(""); try { const remote = await api.getVault(getAccessToken()!); const salt = Uint8Array.from(atob(remote.kdf_salt), c => c.charCodeAt(0)); const key = await deriveVaultKey(password, salt, remote.kdf_params); await unlock(key); onUnlocked(key); navigate("vault") } catch { setError("Incorrect Master Password or unavailable vault") } finally { setLoading(false) } }
  return <div className="unlock-page"><div className="unlock-user"><div className="avatar avatar-lg">VX</div><div><strong>VaultX Account</strong><span>{getPendingEmail()}</span></div></div><div className="unlock-icon"><Icon name="lock" size={32} /></div><div className="auth-copy centered"><h1>Unlock your Vault</h1><p>Enter your Master Password to decrypt and access your vault.</p></div><div className="form-stack"><PasswordField label="Master Password" value={password} onChange={v => { setPassword(v); setError("") }} />{error && <div className="inline-error"><Icon name="alert" />{error}</div>}<Button full onClick={submit} disabled={loading}>{loading ? "Unlocking..." : "Unlock Vault"}</Button></div><button className="subtle-link" onClick={() => { clearAuth(); navigate("login") }}>Not your account? Switch account</button><div className="encrypted-note"><Icon name="shield" /><span><strong>Protected locally</strong>Your vault is decrypted only on this device.</span></div></div>
}

function maskEmail(email: string) { if (!email) return "your email"; const at = email.indexOf("@"); return at <= 2 ? `•••${email.slice(at)}` : `${email.slice(0, 2)}•••${email.slice(at)}` }
function SecurityNote() { return <div className="security-note"><Icon name="shield" /><span><strong>Private by design</strong>Your vault is encrypted before it leaves your device.</span></div> }
