import { useEffect } from "react"
import { usePasswordGenerator } from "../hooks/usePasswordGenerator"
import { Button, Icon, IconButton } from "../../../components/ui/primitives"
export function GeneratorPage({ toast }: { toast: (s: string) => void }) {
  const { length, setLength, visible, setVisible, options, password, strength, strengthClass, toggleOption, regenerate, loading } = usePasswordGenerator()
  useEffect(() => {}, [])
  async function copy() { if (!password) return; await navigator.clipboard.writeText(password); toast("Password copied to clipboard") }
  return <div><div className="page-heading"><div><span className="eyebrow">SECURE TOOL</span><h1>Password Generator</h1><p>Create strong, unique passwords for your accounts.</p></div></div><div className="password-card"><div className="password-top"><span>GENERATED PASSWORD</span><span className={`strength-pill strength-${strengthClass}`}><Icon name={strength === "Weak" ? "alert" : "check"} size={13} />{strength}</span></div><div className="generated"><code>{visible ? password : "•".repeat(Math.min(length, 20))}</code><div><IconButton icon={visible ? "eyeOff" : "eye"} label="Toggle visibility" onClick={() => setVisible(v => !v)} /><IconButton icon="copy" label="Copy password" onClick={copy} /></div></div><div className="entropy"><span><Icon name="shield" size={15} />{strength === "Weak" ? "Needs improvement" : strength === "Fair" ? "Moderate protection" : strength === "Strong" ? "Strong protection" : "Excellent protection"}</span><span>{length} characters</span></div></div><div className="settings-card"><div className="section-line"><h2>Customize</h2><span>Changes apply instantly</span></div><div className="range-label"><label>Password length</label><output>{length}</output></div><input className="range" type="range" min="8" max="32" value={length} onChange={e => setLength(Number(e.target.value))} /><div className="range-scale"><span>8</span><span>32</span></div><div className="options">{(Object.keys(options) as Array<keyof typeof options>).map(option => <label key={option} className={options[option] ? "checked" : ""}><input type="checkbox" checked={options[option]} onChange={() => toggleOption(option)} /><span>{options[option] && <Icon name="check" size={14} />}</span>{option}</label>)}</div></div><div className="generator-actions"><Button variant="secondary" icon="refresh" onClick={() => void regenerate()} disabled={loading}>{loading ? "Generating..." : "Regenerate"}</Button><Button icon="copy" onClick={() => void copy()} disabled={loading}>Copy Password</Button></div></div>
}
