import { useEffect, useState } from "react"
import type { Screen } from "../../../types/navigation"
import { Button, Field, Icon, IconButton, PasswordField } from "../../../components/ui/primitives"
import { useVault } from "../VaultContext"
import type { VaultCredential } from "../../../lib/crypto"
import { LoginRow } from "./components/LoginRow"

export function Vault({ navigate, toast, setDelete }: { navigate: (s: Screen) => void; toast: (s: string) => void; setDelete: (id: string | null) => void }) {
  const { vault, loadVault, setCredential } = useVault(); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("")
  useEffect(() => { loadVault().catch(e => setError(e instanceof Error ? e.message : "Unable to load vault")).finally(() => setLoading(false)) }, [])
  const filtered = vault.credentials.filter(c => `${c.name} ${c.username} ${c.website}`.toLowerCase().includes(query.toLowerCase()))
  const copy = async (value: string, label: string) => { await navigator.clipboard.writeText(value); toast(`${label} copied to clipboard`) }
  return <div><div className="page-heading"><div><span className="eyebrow">PERSONAL VAULT</span><h1>Your Vault</h1><p>Securely manage your saved credentials</p></div><div className="stat"><strong>{vault.credentials.length}</strong><span>Total logins</span></div></div><div className="search-line"><label className="search"><Icon name="search" /><input aria-label="Search your vault" placeholder="Search your vault..." value={query} onChange={e => setQuery(e.target.value)} />{query && <IconButton icon="x" label="Clear search" onClick={() => setQuery("")} />}</label><Button icon="plus" onClick={() => navigate("add")}>Add Login</Button></div><div className="section-line"><h2>All Logins</h2><span>{filtered.length} of {vault.credentials.length}</span></div>{loading ? <div className="empty"><h3>Loading vault…</h3></div> : error ? <div className="empty"><div><Icon name="alert" /></div><h3>Unable to load vault</h3><p>{error}</p><Button variant="secondary" onClick={() => location.reload()}>Retry</Button></div> : <div className="login-list">{filtered.length ? filtered.map(c => <LoginRow key={c.id} service={c} onView={() => { setCredential(c); navigate("view") }} onCopy={() => copy(c.password, "Password")} onDelete={() => setDelete(c.id)} />) : <div className="empty"><div><Icon name="search" /></div><h3>{query ? "No logins found" : "Your vault is empty"}</h3><p>{query ? "Try another search term." : "Add your first login to start using VaultX."}</p><Button variant="secondary" onClick={() => query ? setQuery("") : navigate("add")}>{query ? "Clear search" : "Add Login"}</Button></div>}</div>}<button className="health-card" onClick={() => navigate("security")}><span className="score-ring">{securityScore(vault.credentials)}</span><span><strong>Your vault health is {securityLabel(vault.credentials)}</strong><small>Based on your saved password strength</small></span><Icon name="chevron" /></button></div>
}

export function CredentialForm({ edit, navigate, toast }: { edit?: boolean; navigate: (s: Screen) => void; toast: (s: string) => void }) {
  const { credential, vault, saveVault, setCredential } = useVault(); const [name, setName] = useState(credential?.name ?? ""); const [website, setWebsite] = useState(credential?.website ?? ""); const [username, setUsername] = useState(credential?.username ?? ""); const [password, setPassword] = useState(credential?.password ?? ""); const [category, setCategory] = useState<VaultCredential["category"]>(credential?.category ?? "Personal"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false)
  useEffect(() => { if (edit && !credential) navigate("vault") }, [edit, credential])
  async function generate() { const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*?"; const values = new Uint32Array(20); crypto.getRandomValues(values); setPassword(Array.from(values, n => chars[n % chars.length]).join("")) }
  async function save() { if (!name.trim() || !username.trim() || !password) { setError("Login name, username, and password are required"); return }; setSaving(true); setError(""); try { const next = [...vault.credentials]; const item: VaultCredential = { id: credential?.id ?? crypto.randomUUID(), name: name.trim(), website: website.trim(), username: username.trim(), password, category }; const index = next.findIndex(c => c.id === item.id); if (index >= 0) next[index] = item; else next.unshift(item); await saveVault({ version: 1, credentials: next }); setCredential(item); toast(edit ? "Changes saved successfully" : "Login saved successfully"); navigate("vault") } catch { setError("Unable to save encrypted vault") } finally { setSaving(false) } }
  return <div className="credential-page"><div className="credential-nav"><button className="credential-back" onClick={() => navigate(edit ? "view" : "vault")}><Icon name="arrow" /><span>{edit ? "Edit login" : "Add login"}</span></button><button className="credential-cancel" onClick={() => navigate(edit ? "view" : "vault")}>Cancel</button></div><p className="credential-intro">{edit ? "Update the details for this saved credential." : "Save a new credential to your encrypted vault."}</p><div className="credential-form"><Field label="Login name" placeholder="e.g. GitHub" value={name} onChange={setName} /><Field label="Website" placeholder="https://example.com" value={website} onChange={setWebsite} /><Field label="Username or email" placeholder="you@example.com" value={username} onChange={setUsername} /><PasswordField label="Password" value={password} onChange={setPassword} /><div className="password-meta"><span><Icon name="shield" size={15} />{passwordStrength(password)}</span><button onClick={generate}><Icon name="spark" size={15} />Generate password</button></div><label className="field"><span className="field-label">Category</span><select value={category} onChange={e => setCategory(e.target.value as VaultCredential["category"])}><option>Developer</option><option>Personal</option><option>Work</option><option>Education</option></select></label>{error && <div className="inline-error"><Icon name="alert" />{error}</div>}<Button full onClick={save} disabled={saving}>{saving ? "Saving..." : edit ? "Save changes" : "Save login"}</Button><div className="save-note"><Icon name="shield" size={16} /><span>Saved securely in your encrypted vault. The server never receives your plaintext password.</span></div></div></div>
}

export function ViewLogin({ navigate, toast, setDelete }: { navigate: (s: Screen) => void; toast: (s: string) => void; setDelete: (v: boolean) => void }) {
  const { credential } = useVault(); const [show, setShow] = useState(false); if (!credential) return null
  const copy = async (value: string, label: string) => { await navigator.clipboard.writeText(value); toast(`${label} copied to clipboard`) }
  return <div><button className="back-link in-app" onClick={() => navigate("vault")}>← Back to vault</button><div className="detail-head"><div className={`service-icon service-${credential.category === "Personal" ? "blue" : credential.category === "Education" ? "amber" : "ink"} large`}>{credential.name.slice(0, 2).toUpperCase()}</div><div><h1>{credential.name}</h1><a href={credential.website || "#"} target="_blank" rel="noreferrer">{credential.website || "No website"} ↗</a></div><span className="tag">{credential.category}</span></div><div className="detail-card"><div className="detail-row"><span>Username</span><strong>{credential.username}</strong><IconButton icon="copy" label="Copy username" onClick={() => copy(credential.username, "Username")} /></div><div className="detail-row"><span>Password</span><strong className="mono">{show ? credential.password : "•".repeat(Math.min(credential.password.length, 20))}</strong><IconButton icon={show ? "eyeOff" : "eye"} label={show ? "Hide password" : "Show password"} onClick={() => setShow(v => !v)} /><IconButton icon="copy" label="Copy password" onClick={() => copy(credential.password, "Password")} /></div><div className="detail-row"><span>Website</span><strong>{credential.website || "—"}</strong><span /></div></div><div className="detail-actions"><Button variant="danger" icon="trash" onClick={() => setDelete(true)}>Delete Login</Button><Button icon="edit" onClick={() => navigate("edit")}>Edit Login</Button></div></div>
}

function passwordStrength(password: string) { if (password.length >= 18) return "Very strong password"; if (password.length >= 14) return "Strong password"; if (password.length >= 10) return "Fair password"; return "Weak password" }
function securityScore(credentials: VaultCredential[]) { if (!credentials.length) return 100; const avg = credentials.reduce((sum, c) => sum + Math.min(c.password.length, 20) / 20, 0) / credentials.length; return Math.round(avg * 100) }
function securityLabel(credentials: VaultCredential[]) { const score = securityScore(credentials); return score >= 80 ? "good" : score >= 55 ? "fair" : "needs attention" }
