import { useMemo } from "react"
import type { Screen } from "../../../types/navigation"
import { Button, Icon } from "../../../components/ui/primitives"
import { useVault } from "../../vault/VaultContext"
export function Security({ navigate }: { navigate: (s: Screen) => void }) {
  const { vault, setCredential } = useVault()
  const stats = useMemo(() => { const strong = vault.credentials.filter(c => c.password.length >= 14).length; const weak = vault.credentials.filter(c => c.password.length < 10).length; const counts = new Map<string, number>(); vault.credentials.forEach(c => counts.set(c.password, (counts.get(c.password) ?? 0) + 1)); const reused = vault.credentials.filter(c => (counts.get(c.password) ?? 0) > 1).length; const score = vault.credentials.length ? Math.max(0, Math.round(((strong + (vault.credentials.length - weak) / 2) / Math.max(vault.credentials.length, 1)) * 100)) : 100; return { strong, weak, reused, score } }, [vault])
  return <div><div className="page-heading"><div><span className="eyebrow">VAULT INSIGHTS</span><h1>Security Health</h1><p>Review and improve the security of your saved credentials.</p></div></div><div className="security-score"><div className="score-large"><strong>{stats.score}</strong><span>/ 100</span></div><div><span className="strength-pill"><Icon name={stats.score >= 80 ? "check" : "alert"} size={13} />{stats.score >= 80 ? "Good security" : "Needs attention"}</span><h2>{stats.score >= 80 ? "Your vault is well protected" : "Improve your vault security"}</h2><p>{stats.weak + stats.reused} issue(s) need attention.</p></div></div><div className="metric-grid"><div><span className="metric-icon success"><Icon name="check" /></span><strong>{stats.strong}</strong><small>Strong passwords</small></div><div><span className="metric-icon warning"><Icon name="alert" /></span><strong>{stats.weak}</strong><small>Weak passwords</small></div><div><span className="metric-icon danger"><Icon name="copy" /></span><strong>{stats.reused}</strong><small>Reused passwords</small></div></div><div className="section-line"><h2>Needs attention</h2><span>{stats.weak + stats.reused} issues</span></div>{vault.credentials.filter(c => c.password.length < 10 || vault.credentials.filter(x => x.password === c.password).length > 1).slice(0, 3).map(c => <div className="issue-card" key={c.id}><div className="service-icon service-amber">{c.name.slice(0, 2).toUpperCase()}</div><div><strong>{c.password.length < 10 ? `Improve your ${c.name} password` : `${c.name} password is reused`}</strong><span>{c.password.length < 10 ? "This password is short and may be easy to guess." : "Create a unique password for this account."}</span></div><Button variant="secondary" onClick={() => { setCredential(c); navigate("edit") }}>Fix now</Button></div>)}</div>
}
